import { useEffect, useMemo, useState } from 'react';
import {
  ArrowDownToLine, ArrowUpRight, BarChart3, Bell, CalendarDays, Check, ChevronDown,
  CircleDollarSign, CreditCard, Download, FileText, Home, Menu, Moon, Pencil, Plus,
  Search, Settings as SettingsIcon, Sparkles, Sun, Target, Trash2, TrendingUp, Wallet, X, Zap,
} from 'lucide-react';

type Category = 'Food' | 'Transport' | 'Education' | 'Shopping' | 'Entertainment' | 'Hostel/Rent' | 'Health' | 'Bills' | 'Other';
type Payment = 'Cash' | 'UPI' | 'Debit Card' | 'Credit Card' | 'Other';
type Expense = { id: string; name: string; amount: number; category: Category; date: string; payment: Payment; note?: string };
type Budget = { monthly: number; savingsTarget: number; categories: Record<Category, number> };
type Goal = { name: string; target: number; saved: number };
type Profile = { name: string; course: string; year: string };
type Page = 'Dashboard' | 'Transactions' | 'Analytics' | 'Budgets' | 'Savings Goals' | 'Settings';

const categories: Category[] = ['Food', 'Transport', 'Education', 'Shopping', 'Entertainment', 'Hostel/Rent', 'Health', 'Bills', 'Other'];
const payments: Payment[] = ['Cash', 'UPI', 'Debit Card', 'Credit Card', 'Other'];
const categoryEmoji: Record<Category, string> = { Food: '🍔', Transport: '🚕', Education: '📚', Shopping: '🛍️', Entertainment: '🎬', 'Hostel/Rent': '🏠', Health: '💊', Bills: '📱', Other: '💰' };
const colors: Record<Category, string> = { Food: '#f3cf45', Transport: '#86b8e8', Education: '#efa5c4', Shopping: '#79d59b', Entertainment: '#b9a4e8', 'Hostel/Rent': '#f2ae83', Health: '#91d8d1', Bills: '#ef8c8c', Other: '#c4c8d0' };

const emptyBudget: Budget = { monthly: 0, savingsTarget: 0, categories: { Food: 0, Transport: 0, Education: 0, Shopping: 0, Entertainment: 0, 'Hostel/Rent': 0, Health: 0, Bills: 0, Other: 0 } };
const emptyGoal: Goal = { name: '', target: 0, saved: 0 };
const emptyProfile: Profile = { name: '', course: '', year: '' };
const today = new Date().toISOString().slice(0, 10);
const money = (n: number) => `₹${Math.round(n).toLocaleString('en-IN')}`;
const prettyDate = (d: string) => new Date(`${d}T00:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });

const demoExpenses: Expense[] = [
  { id: '1', name: 'Mess lunch', amount: 180, category: 'Food', date: '2026-08-21', payment: 'UPI', note: 'Thursday special' },
  { id: '2', name: 'Metro recharge', amount: 500, category: 'Transport', date: '2026-08-20', payment: 'UPI' },
  { id: '3', name: 'Operating Systems book', amount: 840, category: 'Education', date: '2026-08-19', payment: 'Debit Card' },
  { id: '4', name: 'Canteen coffee', amount: 120, category: 'Food', date: '2026-08-18', payment: 'Cash' },
  { id: '5', name: 'Movie night', amount: 360, category: 'Entertainment', date: '2026-08-16', payment: 'UPI' },
  { id: '6', name: 'Laundry', amount: 240, category: 'Other', date: '2026-08-15', payment: 'Cash' },
  { id: '7', name: 'Stationery set', amount: 310, category: 'Shopping', date: '2026-08-13', payment: 'UPI' },
  { id: '8', name: 'Hostel electricity', amount: 630, category: 'Bills', date: '2026-08-10', payment: 'UPI' },
  { id: '9', name: 'Badminton court', amount: 200, category: 'Health', date: '2026-08-07', payment: 'Cash' },
];
const demoBudget: Budget = { monthly: 8420, savingsTarget: 2000, categories: { Food: 2500, Transport: 1000, Education: 1500, Shopping: 700, Entertainment: 600, 'Hostel/Rent': 1000, Health: 500, Bills: 800, Other: 500 } };
const demoGoal: Goal = { name: 'New Guitar', target: 10000, saved: 4500 };

function useStored<T>(key: string, fallback: T) {
  const [value, setValue] = useState<T>(() => { try { const item = localStorage.getItem(key); return item ? JSON.parse(item) : fallback; } catch { return fallback; } });
  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]);
  return [value, setValue] as const;
}

function initials(name: string) {
  const parts = name.trim().split(/\s+/);
  if (parts.length >= 2) return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
  return name.trim().slice(0, 2).toUpperCase() || 'S';
}

function App() {
  const [expenses, setExpenses] = useStored<Expense[]>('set-expenses', []);
  const [budget, setBudget] = useStored<Budget>('set-budget', emptyBudget);
  const [goal, setGoal] = useStored<Goal>('set-goal', emptyGoal);
  const [profile, setProfile] = useStored<Profile>('set-profile', emptyProfile);
  const [dark, setDark] = useStored<boolean>('set-dark', false);
  const [page, setPage] = useState<Page>('Dashboard');
  const [showAdd, setShowAdd] = useState(false);
  const [editing, setEditing] = useState<Expense | null>(null);
  const [toast, setToast] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  const remaining = Math.max(0, budget.monthly - total);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };
  const saveExpense = (expense: Expense) => { setExpenses(prev => editing ? prev.map(e => e.id === expense.id ? expense : e) : [expense, ...prev]); setShowAdd(false); setEditing(null); notify(editing ? 'Expense updated' : 'Expense added'); };
  const removeExpense = (id: string) => { if (window.confirm('Delete this expense? This cannot be undone.')) { setExpenses(prev => prev.filter(e => e.id !== id)); notify('Expense deleted'); } };
  const exportCsv = () => { const csv = ['Name,Amount,Category,Date,Payment,Note', ...expenses.map(e => [e.name, e.amount, e.category, e.date, e.payment, e.note ?? ''].map(v => `"${String(v).split('"').join('""')}"`).join(','))].join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const a = document.createElement('a'); a.href = url; a.download = 'student-expenses.csv'; a.click(); URL.revokeObjectURL(url); notify('CSV downloaded'); };
  const displayName = profile.name || 'Student';
  const profileSubtitle = profile.course ? `${profile.course}${profile.year ? ' · ${profile.year} year' : ''}` : 'Set up your profile';
  return <div className={dark ? 'app dark' : 'app'}>
    <aside className={menuOpen ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark"><Wallet size={21} /></div><span>Student<br /><b>Expense Tracker</b></span><button className="icon-btn mobile-close" onClick={() => setMenuOpen(false)} aria-label="Close menu"><X size={18} /></button></div>
      <div className="student-card"><div className="avatar">{initials(displayName)}</div><div><strong>{displayName}</strong><small>{profileSubtitle}</small></div><ChevronDown size={15} /></div>
      <nav>{(['Dashboard', 'Transactions', 'Analytics', 'Budgets', 'Savings Goals', 'Settings'] as Page[]).map((item) => <button key={item} className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => { setPage(item); setMenuOpen(false); }}><NavIcon name={item} /><span>{item}</span>{item === 'Dashboard' && <span className="nav-dot" />}</button>)}</nav>
      <div className="sidebar-bottom"><div className="tip"><Sparkles size={17} /><div><b>Student tip</b><span>Small savings become big wins.</span></div></div><button className="upgrade" onClick={() => notify('You are already using the full student toolkit')}>Your toolkit <ArrowUpRight size={15} /></button></div>
    </aside>
    <main className="main"><header className="topbar"><button className="icon-btn hamburger" onClick={() => setMenuOpen(true)}><Menu size={21} /></button><div><p className="eyebrow">{new Date().toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long' })}</p><h1>{page === 'Dashboard' ? `Welcome back, ${displayName.split(' ')[0]}.` : page}</h1></div><div className="top-actions"><button className="icon-btn" onClick={() => notify('You are all caught up')} aria-label="Notifications"><Bell size={19} /><i /></button><button className="icon-btn" onClick={() => setDark(!dark)} aria-label="Toggle dark mode">{dark ? <Sun size={19} /> : <Moon size={19} />}</button><div className="top-avatar">{initials(displayName)}</div></div></header>
      {page === 'Dashboard' && <Dashboard expenses={expenses} budget={budget} goal={goal} total={total} remaining={remaining} onAdd={() => setShowAdd(true)} onNavigate={setPage} onEdit={setEditing} onDelete={removeExpense} />}
      {page === 'Transactions' && <Transactions expenses={expenses} onAdd={() => setShowAdd(true)} onEdit={setEditing} onDelete={removeExpense} onExport={exportCsv} />}
      {page === 'Analytics' && <Analytics expenses={expenses} budget={budget} total={total} onAdd={() => setShowAdd(true)} />}
      {page === 'Budgets' && <Budgets budget={budget} setBudget={setBudget} expenses={expenses} notify={notify} />}
      {page === 'Savings Goals' && <Goals goal={goal} setGoal={setGoal} total={total} notify={notify} />}
      {page === 'Settings' && <Settings dark={dark} setDark={setDark} expenses={expenses} setExpenses={setExpenses} budget={budget} setBudget={setBudget} goal={goal} setGoal={setGoal} profile={profile} setProfile={setProfile} notify={notify} />}
    </main>
    {!profile.name && <ProfileModal onClose={() => {}} onSave={(p) => { setProfile(p); notify('Profile saved'); }} />}
    {(showAdd || editing) && <ExpenseModal initial={editing} onClose={() => { setShowAdd(false); setEditing(null); }} onSave={saveExpense} />}
    {toast && <div className="toast"><Check size={17} />{toast}</div>}
  </div>;
}

function NavIcon({ name }: { name: Page }) { const props = { size: 18, strokeWidth: 2 }; if (name === 'Dashboard') return <Home {...props} />; if (name === 'Transactions') return <CreditCard {...props} />; if (name === 'Analytics') return <BarChart3 {...props} />; if (name === 'Budgets') return <Wallet {...props} />; if (name === 'Savings Goals') return <Target {...props} />; return <SettingsIcon {...props} />; }

function Dashboard({ expenses, budget, goal, total, remaining, onAdd, onNavigate, onEdit, onDelete }: { expenses: Expense[]; budget: Budget; goal: Goal; total: number; remaining: number; onAdd: () => void; onNavigate: (p: Page) => void; onEdit: (e: Expense) => void; onDelete: (id: string) => void }) {
  const hasData = expenses.length > 0;
  const hasBudget = budget.monthly > 0;
  const hasGoal = goal.target > 0;
  const byCategory = useMemo(() => categories.map(category => ({ category, amount: expenses.filter(e => e.category === category).reduce((s, e) => s + e.amount, 0) })).filter(x => x.amount).sort((a, b) => b.amount - a.amount), [expenses]);
  const highest = byCategory[0]; const lastSeven = expenses.filter(e => new Date(e.date) >= new Date(Date.now() - 7 * 86400000)).reduce((s, e) => s + e.amount, 0); const goalPct = Math.min(100, goal.target ? (goal.saved / goal.target) * 100 : 0);
  return <div className="content"><div className="welcome-row"><div><p className="muted">{hasData ? 'Here’s your money snapshot for this month.' : 'Welcome! Add your first expense to start tracking your spending.'}</p></div><button className="primary" onClick={onAdd}><Plus size={18} /> Add expense</button></div>
    <section className="stat-grid"><StatCard label="Remaining budget" value={money(remaining)} detail={hasBudget ? `${Math.round((remaining / Math.max(budget.monthly, 1)) * 100)}% of your budget left` : 'Set a monthly budget'} color="yellow" icon={<Wallet />} /><StatCard label="Spent this month" value={money(total)} detail={hasData ? `${money(lastSeven)} in the last 7 days` : 'No expenses yet'} color="pink" icon={<ArrowDownToLine />} /><StatCard label="Monthly budget" value={money(budget.monthly)} detail={hasBudget ? `${money(Math.max(0, budget.monthly - total))} available` : 'Not set yet'} color="blue" icon={<CircleDollarSign />} /><StatCard label="Savings goal" value={hasGoal ? money(goal.saved) : '0%'} detail={hasGoal ? `${Math.round(goalPct)}% of ${goal.name}` : 'No goal set'} color="green" icon={<Target />} /></section>
    <div className="dashboard-grid"><section className="panel trend-panel"><PanelTitle title="Spending overview" subtitle={hasData ? 'Your last 7 days at a glance' : 'Your spending will appear here'} action={hasData ? 'View analytics' : undefined} onClick={hasData ? () => onNavigate('Analytics') : undefined} />{hasData ? <MiniChart expenses={expenses} /> : <EmptyState icon={<BarChart3 size={28} />} title="No spending data yet" subtitle="Add a few expenses and your spending trends will appear here." actionLabel="+ Add expense" onAction={onAdd} />}</section><section className="panel insight-panel"><PanelTitle title="Spending insights" subtitle="Personalized for your habits" /><div className="insight-list">{hasData ? <><Insight icon={<TrendingUp />} text={highest ? `${highest.category} is your highest spending category.` : 'Add expenses to unlock your first insight.'} tone="yellow" /><Insight icon={<Sparkles />} text={`You have ${money(remaining)} left for this month.`} tone="pink" /><Insight icon={<Zap />} text={total > budget.monthly * .8 ? `You're close to your monthly budget. Keep an eye on the rest.` : 'You are pacing nicely under your monthly budget.'} tone="blue" /></> : <Insight icon={<Sparkles />} text="Start adding expenses and we'll show you useful spending insights here." tone="yellow" />}</div></section></div>
    <div className="dashboard-grid lower"><section className="panel transactions-preview"><PanelTitle title="Recent transactions" subtitle={hasData ? 'Your latest money moves' : 'Your transactions will show here'} action={hasData ? 'See all' : undefined} onClick={hasData ? () => onNavigate('Transactions') : undefined} />{hasData ? <TransactionRows expenses={expenses.slice(0, 5)} onEdit={onEdit} onDelete={onDelete} /> : <EmptyState icon={<FileText size={28} />} title="No transactions yet" subtitle="Add your first expense to start tracking your spending." actionLabel="+ Add expense" onAction={onAdd} />}</section><section className="panel quick-panel"><PanelTitle title="Quick actions" subtitle="Make your money work for you" /><div className="quick-actions"><QuickAction icon={<Plus />} label="Add expense" color="yellow" onClick={onAdd} /><QuickAction icon={<Wallet />} label="Set a budget" color="blue" onClick={() => onNavigate('Budgets')} /><QuickAction icon={<BarChart3 />} label="View analytics" color="pink" onClick={() => onNavigate('Analytics')} /><QuickAction icon={<Target />} label="Savings goal" color="green" onClick={() => onNavigate('Savings Goals')} /></div>{hasGoal ? <div className="goal-mini"><div className="goal-head"><span>Goal progress</span><b>{Math.round(goalPct)}%</b></div><div className="progress"><i style={{ width: `${goalPct}%` }} /></div><small>{goal.name} · {money(goal.target - goal.saved)} to go</small></div> : <div className="goal-mini"><div className="goal-head"><span>Goal progress</span><b>0%</b></div><div className="progress"><i style={{ width: '0%' }} /></div><small>No savings goal yet</small></div>}</section></div>
    <section className="afford-card"><div className="afford-icon"><CircleDollarSign size={25} /></div><div><p className="eyebrow">Smart check before you spend</p><h2>Can I afford this?</h2><p>See how a purchase would affect your budget, goals, and spending pace.</p></div><button className="secondary" onClick={() => onNavigate('Analytics')}>Try the affordability check <ArrowUpRight size={16} /></button></section>
  </div>;
}

function StatCard({ label, value, detail, color, icon }: { label: string; value: string; detail: string; color: string; icon: React.ReactNode }) { return <div className={`stat-card ${color}`}><div className="stat-top"><span>{label}</span><div className="stat-icon">{icon}</div></div><strong>{value}</strong><small><ArrowUpRight size={13} /> {detail}</small></div>; }
function PanelTitle({ title, subtitle, action, onClick }: { title: string; subtitle: string; action?: string; onClick?: () => void }) { return <div className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action && <button className="text-button" onClick={onClick}>{action} <ArrowUpRight size={14} /></button>}</div>; }
function Insight({ icon, text, tone }: { icon: React.ReactNode; text: string; tone: string }) { return <div className={`insight ${tone}`}><span>{icon}</span><p>{text}</p></div>; }
function QuickAction({ icon, label, color, onClick }: { icon: React.ReactNode; label: string; color: string; onClick: () => void }) { return <button className="quick-action" onClick={onClick}><span className={color}>{icon}</span><b>{label}</b><ArrowUpRight size={14} /></button>; }
function MiniChart({ expenses }: { expenses: Expense[] }) { const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(Date.now() - (6 - i) * 86400000); const key = d.toISOString().slice(0, 10); return { label: d.toLocaleDateString('en-IN', { weekday: 'short' }), amount: expenses.filter(e => e.date === key).reduce((s, e) => s + e.amount, 0) }; }); const max = Math.max(...days.map(d => d.amount), 500); return <div className="chart-wrap"><div className="chart-values"><span>{money(max)}</span><span>{money(max / 2)}</span><span>₹0</span></div><div className="bar-chart">{days.map(day => <div className="bar-col" key={day.label}><div className="bar" style={{ height: `${Math.max(8, (day.amount / max) * 100)}%` }} title={money(day.amount)} /><small>{day.label}</small></div>)}</div></div>; }
function TransactionRows({ expenses, onEdit, onDelete }: { expenses: Expense[]; onEdit: (e: Expense) => void; onDelete: (id: string) => void }) { if (!expenses.length) return <EmptyState icon={<FileText size={28} />} title="No transactions yet" subtitle="Add your first expense to start tracking your spending." />; return <div className="transaction-list">{expenses.map(e => <div className="transaction-row" key={e.id}><span className="category-badge" style={{ background: `${colors[e.category]}55` }}>{categoryEmoji[e.category]}</span><div className="transaction-name"><b>{e.name}</b><small>{e.category} · {prettyDate(e.date)}</small></div><span className="payment">{e.payment}</span><strong className="amount">− {money(e.amount)}</strong><div className="row-actions"><button onClick={() => onEdit(e)} aria-label="Edit"><Pencil size={14} /></button><button onClick={() => onDelete(e.id)} aria-label="Delete"><Trash2 size={14} /></button></div></div>)}</div>; }

function EmptyState({ icon, title, subtitle, actionLabel, onAction }: { icon: React.ReactNode; title: string; subtitle: string; actionLabel?: string; onAction?: () => void }) {
  return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{subtitle}</p>{actionLabel && onAction && <button className="primary" onClick={onAction}><Plus size={16} /> {actionLabel.replace('+ ', '')}</button>}</div>;
}

function Transactions({ expenses, onAdd, onEdit, onDelete, onExport }: { expenses: Expense[]; onAdd: () => void; onEdit: (e: Expense) => void; onDelete: (id: string) => void; onExport: () => void }) { const [search, setSearch] = useState(''); const [category, setCategory] = useState('All'); const [sort, setSort] = useState('date'); const filtered = expenses.filter(e => e.name.toLowerCase().includes(search.toLowerCase()) && (category === 'All' || e.category === category)).sort((a, b) => sort === 'amount' ? b.amount - a.amount : b.date.localeCompare(a.date)); return <div className="content"><div className="page-actions"><div><p className="muted">Every purchase, all in one place.</p></div><div className="button-row"><button className="secondary" onClick={onExport} disabled={!expenses.length}><Download size={16} /> Export CSV</button><button className="primary" onClick={onAdd}><Plus size={17} /> Add expense</button></div></div><section className="panel table-panel"><div className="filters"><div className="search"><Search size={17} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search transactions" /></div><select value={category} onChange={e => setCategory(e.target.value)}><option>All</option>{categories.map(c => <option key={c}>{c}</option>)}</select><select value={sort} onChange={e => setSort(e.target.value)}><option value="date">Newest first</option><option value="amount">Highest amount</option></select></div>{filtered.length ? <TransactionRows expenses={filtered} onEdit={onEdit} onDelete={onDelete} /> : <EmptyState icon={<FileText size={28} />} title="No transactions yet" subtitle="Add your first expense to start tracking your spending." actionLabel="+ Add expense" onAction={onAdd} />}</section></div>; }

function Analytics({ expenses, budget, total, onAdd }: { expenses: Expense[]; budget: Budget; total: number; onAdd: () => void }) { const [product, setProduct] = useState(''); const [price, setPrice] = useState(''); const [result, setResult] = useState<{ tone: string; title: string; body: string } | null>(null); const grouped = categories.map(c => ({ category: c, amount: expenses.filter(e => e.category === c).reduce((s, e) => s + e.amount, 0) })).sort((a, b) => b.amount - a.amount); const max = Math.max(...grouped.map(x => x.amount), 1); const hasData = expenses.length > 0; const check = () => { const amount = Number(price); if (!amount || amount <= 0) return; const remaining = budget.monthly - total; const ratio = amount / Math.max(remaining, 1); setResult(ratio < .2 ? { tone: 'good', title: 'Comfortable', body: `This would use ${Math.round(ratio * 100)}% of your remaining monthly budget. You can make this purchase without derailing your plan.` } : ratio < .5 ? { tone: 'warn', title: 'Think twice', body: `This would use ${Math.round(ratio * 100)}% of what you have left this month. Consider waiting a few days.` } : { tone: 'bad', title: 'Not recommended', body: `This would use ${Math.round(ratio * 100)}% of your remaining budget and could put your savings goal at risk.` }); };
  if (!hasData) return <div className="content"><div className="page-actions"><div><p className="muted">Understand where your money goes.</p></div><button className="primary" onClick={onAdd}><Plus size={17} /> Add expense</button></div><section className="panel"><EmptyState icon={<BarChart3 size={28} />} title="No spending data yet" subtitle="Add a few expenses and your spending trends will appear here." actionLabel="+ Add expense" onAction={onAdd} /></section></div>;
  return <div className="content"><div className="analytics-grid"><section className="panel chart-panel"><PanelTitle title="Spending by category" subtitle="Where your money is going this month" /><div className="category-bars">{grouped.filter(x => x.amount > 0).map(x => <div className="category-bar" key={x.category}><div className="bar-label"><span>{categoryEmoji[x.category]} {x.category}</span><b>{money(x.amount)}</b></div><div className="track"><i style={{ width: `${(x.amount / max) * 100}%`, background: colors[x.category] }} /></div></div>)}</div></section><section className="panel check-panel"><PanelTitle title="Can I afford this?" subtitle="A calmer way to make bigger purchases" /><label>What are you thinking of buying?<input value={product} onChange={e => setProduct(e.target.value)} placeholder="e.g. Headphones" /></label><label>Price<input type="number" min="1" value={price} onChange={e => setPrice(e.target.value)} placeholder="₹ 2,000" /></label><button className="primary full" onClick={check}>Check my purchase <Sparkles size={16} /></button>{result && <div className={`afford-result ${result.tone}`}><strong>{result.tone === 'good' ? '✓' : result.tone === 'warn' ? '!' : '×'} {result.title}</strong><p>{result.body}</p></div>}</section></div><div className="analytics-grid"><section className="panel"><PanelTitle title="Budget progress" subtitle="Stay aware before the month gets away" /><div className="budget-list">{grouped.slice(0, 6).map(x => { const cap = budget.categories[x.category] || 1; const pct = Math.min(100, (x.amount / cap) * 100); return <div className="budget-item" key={x.category}><div><span>{categoryEmoji[x.category]} {x.category}</span><small>{money(x.amount)} / {money(cap)}</small></div><div className="track"><i className={pct >= 100 ? 'over' : ''} style={{ width: `${pct}%`, background: colors[x.category] }} /></div></div>; })}</div></section><section className="panel"><PanelTitle title="Monthly rhythm" subtitle="Simple signals from your spending" /><div className="rhythm"><div className="rhythm-number">{money(total)}<small>spent so far</small></div><div className="rhythm-row"><span>Daily average</span><b>{money(total / Math.max(new Date().getDate(), 1))}</b></div><div className="rhythm-row"><span>Budget used</span><b>{Math.round((total / Math.max(budget.monthly, 1)) * 100)}%</b></div><div className="rhythm-row"><span>Largest category</span><b>{grouped[0]?.category ?? '—'}</b></div></div></section></div></div>; }

function Budgets({ budget, setBudget, expenses, notify }: { budget: Budget; setBudget: (b: Budget) => void; expenses: Expense[]; notify: (m: string) => void }) { const [draft, setDraft] = useState(budget); const totals = Object.fromEntries(categories.map(c => [c, expenses.filter(e => e.category === c).reduce((s, e) => s + e.amount, 0)])) as Record<Category, number>; const save = () => { setBudget(draft); notify('Budget settings saved'); }; const hasBudget = budget.monthly > 0; return <div className="content"><div className="page-actions"><p className="muted">Give every rupee a job before the month begins.</p><button className="primary" onClick={save}><Check size={17} /> Save budgets</button></div><div className="budget-layout"><section className="panel budget-editor"><PanelTitle title="Monthly plan" subtitle="Your big-picture spending limits" /><label>Overall monthly budget<input type="number" min="0" value={draft.monthly} onChange={e => setDraft({ ...draft, monthly: Number(e.target.value) })} placeholder="₹ 0" /></label><label>Monthly savings target<input type="number" min="0" value={draft.savingsTarget} onChange={e => setDraft({ ...draft, savingsTarget: Number(e.target.value) })} placeholder="₹ 0" /></label><div className="category-editor"><h3>Category budgets</h3>{categories.map(c => <label key={c}><span>{categoryEmoji[c]} {c}</span><input type="number" min="0" value={draft.categories[c]} onChange={e => setDraft({ ...draft, categories: { ...draft.categories, [c]: Number(e.target.value) } })} placeholder="₹ 0" /></label>)}</div></section><section className="panel">{hasBudget ? <><PanelTitle title="This month" subtitle="Budget health at a glance" /><div className="big-progress"><div className="donut" style={{ '--progress': `${Math.min(100, (expenses.reduce((s, e) => s + e.amount, 0) / Math.max(draft.monthly, 1)) * 100)}%` } as React.CSSProperties}><b>{Math.round((expenses.reduce((s, e) => s + e.amount, 0) / Math.max(draft.monthly, 1)) * 100)}%</b><small>used</small></div><p>You've spent <b>{money(expenses.reduce((s, e) => s + e.amount, 0))}</b> of your {money(draft.monthly)} monthly budget.</p></div><div className="budget-list compact">{categories.slice(0, 5).map(c => <div className="budget-item" key={c}><div><span>{categoryEmoji[c]} {c}</span><small>{Math.round((totals[c] / Math.max(draft.categories[c], 1)) * 100)}%</small></div><div className="track"><i className={totals[c] > draft.categories[c] ? 'over' : ''} style={{ width: `${Math.min(100, (totals[c] / Math.max(draft.categories[c], 1)) * 100)}%`, background: colors[c] }} /></div></div>)}</div></> : <><PanelTitle title="Set your monthly budget" subtitle="Plan your spending before the month begins" /><EmptyState icon={<Wallet size={28} />} title="Set your monthly budget" subtitle="Enter your overall monthly budget on the left and save to start tracking your spending limits." /></>}</section></div></div>; }

function Goals({ goal, setGoal, total, notify }: { goal: Goal; setGoal: (g: Goal) => void; total: number; notify: (m: string) => void }) { const [draft, setDraft] = useState(goal); const pct = Math.min(100, (draft.saved / Math.max(draft.target, 1)) * 100); const hasGoal = goal.target > 0; return <div className="content"><div className="page-actions"><p className="muted">Make room for the things that matter to you.</p><button className="primary" onClick={() => { setGoal(draft); notify('Savings goal saved'); }}><Check size={17} /> Save goal</button></div><div className="goal-layout"><section className="panel goal-hero"><div className="target-icon"><Target size={30} /></div><p className="eyebrow">Current savings goal</p><h2>{hasGoal ? (draft.name || 'Your next big thing') : 'No savings goal yet'}</h2>{hasGoal ? <><div className="goal-amount"><b>{money(draft.saved)}</b><span>of {money(draft.target)}</span></div><div className="progress large"><i style={{ width: `${pct}%` }} /></div><div className="goal-meta"><span>{Math.round(pct)}% complete</span><b>{money(Math.max(0, draft.target - draft.saved))} to go</b></div><div className="goal-message"><Sparkles size={17} /> At this pace, your goal is closer than it feels.</div></> : <p className="muted" style={{ marginTop: '10px' }}>Create a goal and track your progress.</p>}</section><section className="panel goal-form"><PanelTitle title="Edit your goal" subtitle="Keep your motivation visible" /><label>Goal name<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} placeholder="e.g. New Guitar" /></label><label>Target amount<input type="number" min="1" value={draft.target} onChange={e => setDraft({ ...draft, target: Number(e.target.value) })} placeholder="₹ 0" /></label><label>Already saved<input type="number" min="0" value={draft.saved} onChange={e => setDraft({ ...draft, saved: Number(e.target.value) })} placeholder="₹ 0" /></label>{hasGoal && <div className="goal-note"><TrendingUp size={16} /><span>Your savings target is {money(Math.max(0, draft.target - draft.saved))} away. Keep going.</span></div>}</section></div>{hasGoal && <section className="afford-card soft"><div className="afford-icon"><Wallet size={23} /></div><div><h2>One small habit</h2><p>Moving even {money(Math.max(50, Math.round(total * .02)))} into your goal each week keeps the momentum alive.</p></div></section>}</div>; }

function Settings({ dark, setDark, expenses, setExpenses, budget, setBudget, goal, setGoal, profile, setProfile, notify }: { dark: boolean; setDark: (v: boolean) => void; expenses: Expense[]; setExpenses: (e: Expense[]) => void; budget: Budget; setBudget: (b: Budget) => void; goal: Goal; setGoal: (g: Goal) => void; profile: Profile; setProfile: (p: Profile) => void; notify: (m: string) => void }) {
  const [editProfile, setEditProfile] = useState(false);
  const [draftProfile, setDraftProfile] = useState(profile);
  return <div className="content"><section className="panel settings-panel"><PanelTitle title="Your profile" subtitle="Tell the tracker who you are" />{editProfile ? <><label style={{ fontSize: '11px', fontWeight: 700, display: 'flex', flexDirection: 'column', gap: '7px', marginBottom: '14px' }}>Name<input value={draftProfile.name} onChange={e => setDraftProfile({ ...draftProfile, name: e.target.value })} placeholder="Your name" style={{ border: '1px solid #d7d5cd', borderRadius: '9px', padding: '10px', fontSize: '12px', outline: '0', color: 'inherit', minWidth: '140px' }} /></label><label style={{ fontSize: '11px', fontWeight: 700, display: 'flex', flexDirection: 'column', gap: '7px', marginBottom: '14px' }}>Course / field of study<input value={draftProfile.course} onChange={e => setDraftProfile({ ...draftProfile, course: e.target.value })} placeholder="e.g. Computer Science" style={{ border: '1px solid #d7d5cd', borderRadius: '9px', padding: '10px', fontSize: '12px', outline: '0', color: 'inherit', minWidth: '140px' }} /></label><label style={{ fontSize: '11px', fontWeight: 700, display: 'flex', flexDirection: 'column', gap: '7px', marginBottom: '14px' }}>Year of study<input value={draftProfile.year} onChange={e => setDraftProfile({ ...draftProfile, year: e.target.value })} placeholder="e.g. 3rd" style={{ border: '1px solid #d7d5cd', borderRadius: '9px', padding: '10px', fontSize: '12px', outline: '0', color: 'inherit', minWidth: '140px' }} /></label><div className="button-row"><button className="secondary" onClick={() => { setEditProfile(false); setDraftProfile(profile); }}>Cancel</button><button className="primary" onClick={() => { setProfile(draftProfile); setEditProfile(false); notify('Profile saved'); }}><Check size={16} /> Save profile</button></div></> : <div className="setting-row"><div><b>{profile.name || 'Student'}</b><p>{profile.course ? `${profile.course}${profile.year ? ' · ${profile.year} year' : ''}` : 'Not set yet'}</p></div><button className="secondary" onClick={() => { setDraftProfile(profile); setEditProfile(true); }}><Pencil size={14} /> Edit profile</button></div>}</section>
    <section className="panel settings-panel"><PanelTitle title="Your preferences" subtitle="Make the tracker feel like yours" /><div className="setting-row"><div><b>Dark mode</b><p>Use a softer dark canvas for evening check-ins.</p></div><button className={dark ? 'toggle on' : 'toggle'} onClick={() => setDark(!dark)}><i /></button></div><div className="setting-row"><div><b>Reminders</b><p>Gentle nudges to log expenses regularly.</p></div><button className="toggle on" onClick={() => notify('Reminders are enabled')}><i /></button></div><div className="setting-row"><div><b>Data stored on this device</b><p>Your information stays in this browser and survives refreshes.</p></div><span className="safe-badge"><Check size={14} /> Private</span></div></section>
    <section className="panel settings-panel"><PanelTitle title="Demo data" subtitle="Load sample data to explore the app" /><div className="setting-row"><div><b>Load demo data</b><p>Replace your current data with sample transactions, budget, and a savings goal.</p></div><button className="secondary" onClick={() => { if (window.confirm('Replace your current data with demo data?')) { setExpenses(demoExpenses); setBudget(demoBudget); setGoal(demoGoal); notify('Demo data loaded'); } }}>Load demo data</button></div>{(expenses.length > 0 || budget.monthly > 0 || goal.target > 0) && <div className="danger-zone"><div><b>Clear all data</b><p>Remove all transactions, budget, and savings goal to start fresh.</p></div><button className="secondary" onClick={() => { if (window.confirm('Clear all your data? This cannot be undone.')) { setExpenses([]); setBudget(emptyBudget); setGoal(emptyGoal); notify('All data cleared'); } }}>Clear all</button></div>}</section>
  </div>;
}

function ProfileModal({ onClose, onSave }: { onClose: () => void; onSave: (p: Profile) => void }) {
  const [name, setName] = useState('');
  const [course, setCourse] = useState('');
  const [year, setYear] = useState('');
  const [error, setError] = useState('');
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!name.trim()) return setError('Please enter your name.'); onSave({ name: name.trim(), course: course.trim(), year: year.trim() }); };
  return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">First-time setup</p><h2>Welcome! Let's get started</h2></div></div>{error && <div className="form-error">{error}</div>}<label>Name<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label><label>Course / field of study<input value={course} onChange={e => setCourse(e.target.value)} placeholder="e.g. Computer Science" /></label><label>Year of study<input value={year} onChange={e => setYear(e.target.value)} placeholder="e.g. 3rd year" /></label><p className="muted" style={{ fontSize: '11px' }}>You can change these anytime in Settings.</p><div className="modal-actions"><button type="submit" className="primary"><Check size={16} /> Get started</button></div></form></div>;
}

function ExpenseModal({ initial, onClose, onSave }: { initial: Expense | null; onClose: () => void; onSave: (e: Expense) => void }) { const [form, setForm] = useState<Expense>(initial ?? { id: crypto.randomUUID(), name: '', amount: 0, category: 'Food', date: today, payment: 'UPI', note: '' }); const [error, setError] = useState(''); const update = <K extends keyof Expense>(key: K, value: Expense[K]) => setForm(prev => ({ ...prev, [key]: value })); const submit = (e: React.FormEvent) => { e.preventDefault(); if (!form.name.trim()) return setError('Give this expense a name.'); if (!form.amount || form.amount <= 0) return setError('Enter an amount greater than zero.'); onSave({ ...form, name: form.name.trim() }); }; return <div className="modal-backdrop" onMouseDown={e => e.target === e.currentTarget && onClose()}><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">{initial ? 'Update a purchase' : 'Track a purchase'}</p><h2>{initial ? 'Edit expense' : 'Add expense'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={19} /></button></div>{error && <div className="form-error">{error}</div>}<label>Expense name<input autoFocus value={form.name} onChange={e => update('name', e.target.value)} placeholder="e.g. Lunch with friends" /></label><div className="form-grid"><label>Amount<input type="number" min="1" value={form.amount || ''} onChange={e => update('amount', Number(e.target.value))} placeholder="₹ 0" /></label><label>Date<input type="date" value={form.date} onChange={e => update('date', e.target.value)} /></label></div><div className="form-grid"><label>Category<select value={form.category} onChange={e => update('category', e.target.value as Category)}>{categories.map(c => <option key={c}>{categoryEmoji[c]} {c}</option>)}</select></label><label>Payment method<select value={form.payment} onChange={e => update('payment', e.target.value as Payment)}>{payments.map(p => <option key={p}>{p}</option>)}</select></label></div><label>Note <span className="optional">Optional</span><textarea value={form.note} onChange={e => update('note', e.target.value)} placeholder="Add a little context" rows={3} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">{initial ? 'Save changes' : 'Add expense'} <Check size={16} /></button></div></form></div>; }

export default App;
